import Head from 'next/head'
import './globals.scss'
import { Open_Sans } from 'next/font/google'

const generic = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={generic.className}>
        {children}
      </body>
    </html>
  )
}
